### ISSUE TITLE
MerginMapsにQGISプロジェクトファイル一式アップロードしてみました

### ISSUE THREAD

**Issue by JinIgarashi** [wata909/R060101_Noto_Peninsula_EQ_QGIS#3]
MerginMapsの日本語翻訳をするのにLutraConsultingから無償で利用できる枠をもらっているので、それを活用して、このプロジェクトファイル一式アップロードしてみました。

![image](https://github.com/wata909/R060101_Noto_Peninsula_EQ_QGIS/assets/2639701/b5aa9603-d7bf-4b32-86cf-ed4a55eb32b9)

「令和6年能登半島地震GISデータ」という名前でPublicにしています。手持ちのiPhone版のアプリでみたところ、ちゃんと表示できているようです。何も設定を変えずにただドラッグ&ドロップしただけなのに、モバイルでもちゃんと表示できるのに驚きました。

MerginMapsのアカウントお持ちであれば、プロジェクトのワークスペースにユーザー追加できますので、教えてください。MerginMaps使えば自動でクラウドとQGIS・モバイルアプリ間で同期もできるし、結構便利だと思います。

![image](https://github.com/wata909/R060101_Noto_Peninsula_EQ_QGIS/assets/2639701/cd55b6c3-fd1b-4de2-8349-d51edd2de7a2)

![image](https://github.com/wata909/R060101_Noto_Peninsula_EQ_QGIS/assets/2639701/49bf3d33-0fc2-473d-9931-4f8f926a22c1)

![image](https://github.com/wata909/R060101_Noto_Peninsula_EQ_QGIS/assets/2639701/161db5ca-1cb0-4a57-a60c-ed757a78ae00)

**Comment by JinIgarashi** [comment]
ちなみにQGISで見た様子はこんな感じ。ワークスペースのメンバーなら簡単にダウンロードして更新して、アップロードできます。

![image](https://github.com/wata909/R060101_Noto_Peninsula_EQ_QGIS/assets/2639701/ed7ef7ff-f3c2-40c3-8e41-ba8485ea6cd2)

**Comment by wata909** [comment]
アカウント、wata909で登録してみました。よければご招待ください！

**Comment by JinIgarashi** [comment]
@wata909 招待するのにEメールアドレスが必要みたいです。Github上でメールアドレスをやりとりするのは微妙なので、Twitterでメッセージ送りました。

**Comment by wata909** [comment]
承知しました。ここでcloseにしますね。
