### ISSUE TITLE
ラベル用のフォント

### ISSUE THREAD

**Issue by tosseto** [wata909/R060101_Noto_Peninsula_EQ_QGIS#4]
レイヤ石川県を読み込んだ際に，MS UI Gothicが適用されており，MacOSでは利用できないという表示がでるようです。OSごとに対応するのは大変かと思いますし，ノーマルフォントを使われてはいかがでしょうか？

![スクリーンショット 2024-01-10 10 05 47](https://github.com/wata909/R060101_Noto_Peninsula_EQ_QGIS/assets/1242052/f0bae3ed-4c45-483a-95bb-5727a91ae1f4)

**Comment by wata909** [comment]
ありがとうございます。確認します！

**Comment by wata909** [comment]
修正しました。こちらのMac環境では出ていません。ご確認頂けますか？

**Comment by tosseto** [comment]
早速対応いただきありがとうございます。こちらでもエラー表示出ませんでしたのでCloseします。
